### ISSUE TITLE
Connection to IPC socket failed for pathname

### ISSUE THREAD

**Issue by lsircc** [nalepae/pandarallel#42] opened 2019-08-15 09:22 UTC
Hello, ask, pandarallel.initialize () appears warning how is it? Thank you: WARNING: Logging before InitGoogleLogging() is written to STDERR
E0812 19:11:57.484051 2409853824 http://io.cc:168] Connection to IPC socket failed for pathname /var/folders/sp/vz74h1tx3jlb3jqrq__bjwh00000gp/T/pandarallel-32ts0h6r/plasma_sock, retrying 20 more times
please help me,thank

**Comment by lsircc** [comment] 2019-08-15 09:24
In addition, an error occurred after more than 54 cycles:
Traceback (most recent call last):
  File "/Users/lsir/.local/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/lsir/.local/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/lsir/.local/lib/python3.7/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/Users/lsir/.local/lib/python3.7/site-packages/pandarallel/dataframe.py", line 19, in worker_apply
    client = plasma.connect(plasma_store_name)
  File "pyarrow/_plasma.pyx", line 805, in pyarrow._plasma.connect
  File "pyarrow/error.pxi", line 87, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Encountered unexpected EOF

**Comment by lsircc** [comment] 2019-08-15 09:32
The current workaround is to increase every loop: pandarallel.initialize()

**Comment by CookieChief** [comment] 2019-08-28 13:29
@lsircc  what do you mean by "increase every loop"? What needs to be increased?

**Comment by lsircc** [comment] 2019-08-28 20:56
Sorry. Machine translation is not accurate. My original intent is to add a line to each function: pandarallel.initialize(). That is, each function is initialized before it runs, so that only warnings are guaranteed. thank you for your reply. The biggest question now is how to deal with the warning? Thank you
----------
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0829 04:54:52.643167 3059774336 io.cc:168] Connection to IPC socket failed for pathname /var/folders/sp/vz74h1tx3jlb3jqrq__bjwh00000gp/T/pandarallel-32ts0h6r/plasma_sock, retrying 20 more times

**Comment by lsircc** [comment] 2019-08-28 20:59
@CookieChief pandarallel.initialize(shm_size_mb=1024,progress_bar=False, verbose=0)
-----
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0829 04:54:52.643167 3059774336 io.cc:168] Connection to IPC socket failed for pathname /var/folders/sp/vz74h1tx3jlb3jqrq__bjwh00000gp/T/pandarallel-32ts0h6r/plasma_sock, retrying 20 more times

**Comment by lsircc** [comment] 2019-08-28 21:01
@CookieChief My version:
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda custom (64-bit) on darwin
Type "help", "copyright", "credits" or "license" for more information.
MACOS 10.13.6 Thank.

**Comment by nalepae** [comment] 2019-09-16 22:53
I'm currently developing a new version of **Pandarallel** without **PyArrow Plasma** (which seems to be the cause of your bug).

This version is not yet relased, but you can already try it by:
- Cloning this git repository on your computer
- Switching to **develop** branch
- Running `$ pip install .` (with the dot after the install)

By default, this version of **Pandarallel** will try to use `/dev/shm` to transfer data between the main process and the workers. If you don't want to use this feature but you prefer to use standard multiprocessing tranfert feature (pipe), you can disable it by passing `use_memory_fs_is_available=False` in the initialize method.

See the docstring of `initialize` for more information.

Note the `shm_size_mb` parameter of `initialize` is now deprecated since **Pandarallel** don't use **PyArrow** anymore.

In you chosoe to use `/dev/shm` to transfer data between the main process and the workers and you got a memory error, you can either:
- Increase the size of this partition, thanks to [this link](https://tontr.blogspot.com/2016/07/how-to-resize-tmpfs-devshm-in-linux.html), or
- Use standard multiprocessing tranfert feature (pipe), by passing `use_memory_fs_is_available=False` in the initialize method.

Note that I did **not** re-implemented (yet) progress bar and verbosity option in this version.

To remove this develop version and retrieve the official one:
- `$ pip uninstall pandarallel`
- `$ pip install pandarallel`

Please let me know if you encounter a new bug or if it works better now.

Regards,

Manu

**Comment by nalepae** [comment] 2019-11-09 22:54
Fixed with `pandarallel 1.4.0`

It seems your bug comes from the usage of `pyarrow plasma`.

`pandarallel 1.4.0` does not use `pyarrow plasma` any more.

**Closed by nalepae** 2019-11-09 22:54 UTC

**Comment by lsircc** [comment] 2019-11-10 06:10
Thank you! let me try.

**Comment by lsircc** [comment] 2019-11-10 06:27
Thank you.Very Good.
