### ISSUE TITLE
df.parallel_apply occured AttributeError: Can't pickle local object 'prepare_worker.<locals>.closure.<locals>.wrapper'

### ISSUE THREAD

**Issue by mliwang** [nalepae/pandarallel#98] opened 2020-06-19 10:40 UTC
when I use df.parallel_apply(lambda x:assinLabel(x),axis=1) 
It occurred AttributeError: Can't pickle local object 'prepare_worker.<locals>.closure.<locals>.wrapper'

**Comment by marc-rauckhorst** [comment] 2020-06-29 22:05
I'm experiencing this as well. Using Python 3.8.2 on Mac OS X Catalina inside a fully updated Conda virtual env within VS Code.

**Comment by vivianamarquez** [comment] 2020-07-23 14:40
I also came across this issue. Using Python 3.7.6 on a Windows 10 Pro.

**Comment by Anthony2cc** [comment] 2020-07-31 07:06
I'm experiencing this as well. Using Python 3.8.2 on MacOS 10.15.6 within jupyternotebook

**Comment by hrajpal96** [comment] 2020-08-09 20:05
I am experiencing the same issue on my machine.
Configuration: -
OS: Windows 10
Python: 3.7.6

**Comment by om-hb** [comment] 2020-09-21 12:43
Same problem here when executing `res_parallel = df.parallel_apply(func, axis=1)` in the provided _examples_ Notebook.

pandarallel: 1.4.8
OS: Windows 10
Python: 3.6.10
Enviroment: Jupyter Notebook inside of VS Code

**Comment by mikelehen** [comment] 2020-10-24 19:05
NOTE: This looks like a dupe of https://github.com/nalepae/pandarallel/issues/72

I'm running into this as well. In case it's of any help, I think the issue may only occur when you are using the "spawn" start method of multiprocessing (i.e. multiprocessing.set_start_method("spawn")) which is the default mode under Windows and macOS (at least in python 3.8 and newer since "fork" is unreliable on macOS--see https://bugs.python.org/issue33725).

Would be great to see a fix for this implemented.

**Comment by nalepae** [comment] 2022-03-14 20:30
Fixed on both Mac and Windows on `pandarallel v1.6.0`.

For Windows, be sure to checkout the documentation.

**Closed by nalepae** 2022-03-14 20:30 UTC
