### ISSUE TITLE
AttributeError: 'RollingGroupby' object has no attribute '_groupby'

### ISSUE THREAD

**Issue by BeckyYu96** [nalepae/pandarallel#152] opened 2021-08-06 05:38 UTC
When I'm running 'parallel_apply' on a RollingGroupby object, it throws the error as Title shows.

Simply test with the code in samples.
`df_size = int(1e6)`
`dff = pd.DataFrame( dict(a=np.random.randint(1,300,df_size),
                                          b=np.random.rand(df_size)))`
`res_parallel = dff.groupby('a').b.rolling(4).parallel_apply(func, raw=False)`

pandas version: 1.3.1

**Comment by jorenham** [comment] 2021-10-04 01:48
This is the cause
https://github.com/pandas-dev/pandas/commit/272435073c70b4421f72184663837f4864601f11#diff-376f031d24a9c167d8ea06982971b613702f7dd122e168c3a8b333009a811ed4L557

**Comment by nalepae** [comment] 2021-10-17 19:35
Fixed in **pandarallel v1.5.4**.

**Closed by nalepae** 2021-10-17 19:35 UTC
